export const projects = [
  {
    title: 'Beadsworld Shop',
    description: "Using React, Node.js, HTML, CSS to design a commercial Beads web shop, make signup, singin, shop and cart page, also make it navaigate funtionality. At meantime, design it to fit for ipad or phone operation. ",
    image: './images/Picture1.png',
    tags: ['HTML', 'CSS', 'React', 'Node'],
    source: 'https://github.com/enzymelab/BeadsWorld',
    visit: 'https://github.com/enzymelab/BeadsWorld',
    id: 0,
  },
  {
    title: 'CLothing Shop',
    description: "While building it I learned many advanced CSS & JavaScript topics, as well as how to make shop to cart works well. e-commerce applications are impressive.",
    image: './images/Picture2.png',
    tags: ['CSS', 'JavaScript'],
    source: 'https://www.youtube.com/watch?v=cT_ZYrS3tKc',
    visit: 'https://github.com/enzymelab/myproject',
    id: 1,
  },
  {
    title: 'Modern UI/UX GPT-3',
    description: "Learn and follow this Modern UI/UX GPT-3 webpage design on Youtube.",
    image: './images/Picture3.png',
    tags: ['React', 'HTML', 'CSS'],
    source: 'https://www.youtube.com/watch?v=F627pKNUCVQ',
    visit: 'https://github.com/enzymelab/summer',
    id: 2,
  },
  {
    title: 'Portfolio website',
    description: "I learned Scss, Javascript from this project. I found Scss is so easy to use and much clear compared with CSS.",
    image: './images/Picture5.png',
    tags: ['Scss', 'Javascript ', 'Nodejs'],
    source: 'https://www.youtube.com/watch?v=xV7S8BhIeBo',
    visit: 'https://github.com/enzymelab/myproject',
    id: 3,
  },
  {
    title: 'image management system CorkBoardIt',
    description: "CorkBoardIt is a simplified site with support for the most important features of an image organization and sharing site: users, CorkBoards, PushPins (to attach a picture to a CorkBoard), and the ability to follow other users, watch CorkBoards, and comment on the images on CorkBoards. The system is implemented using a fully relational, distinct Database Management System (DBMS) that utilizes tables and supports standard SQL queries.",
    image: './images/Picture6.png',
    tags: ['SQL', 'Javascript ', 'PHP', 'python'],
    source: 'https://www.youtube.com/watch?v=ckVWYmiYZOI',
    visit: 'https://www.youtube.com/watch?v=ckVWYmiYZOI',
    id: 4,
  }, {
    title: 'Angular food shop',
    description: "Currently I am working on this Tutorial study, try to master angular and boostrap application. Main fuction including Admin: Product CRUD, User Management, Order Management, Total Revenue.      User: register, login, logout, Add to cart, product checkout",
    image: './images/Picture4.png',
    tags: ['Angular', 'Mongodb ', 'Nodejs'],
    source: 'https://www.youtube.com/watch?v=NFh9WEH0Zi4',
    visit: 'https://github.com/nasirjd/foodmine-course',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked on Bioinformatics using python', },
  { year: 2019, text: 'Learning SQL,HTML,CSS', },
  { year: 2021, text: 'Learning JavaScript, ReactJS, NodeJS', },
  { year: 2022, text: 'Started webpage design', },
];